# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu 
menu:
- page: Flipped205的个人主页
  url: /
  icon: 
- page: 前端
  url: /categories/前端/
  icon: 
- page: Linux
  url: /categories/Linx/
  icon: 
- page: 书籍
  url: /categories/书籍/
  icon: 
- page: 笔记
  url: /categories/笔记/
  icon: 
- page: 杂读
  url: /categories/杂读/
  icon: 
- page: 工具
  url: /categories/工具/
  icon: 

## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml


# 各个小工具的设置

## widgets
widgets:
  - about
  - search
  - category
  - archive
  - tagcloud

## 网站公告设置
about: |-
      <h3>FLIPPED</h3>
      <div>
      <div style="float:left; clear: both;" align="center">
      <img src="/img/about.jpg" style="width: 80%;">
      </div>
      <p style="align:center;line-height: 25px;font-size: 13.6px">The higher I got, the more amazed I was by the view.Some of us get dipped in flat, some in satin, some in gloss. But every once in a while you find someone who's iridescent, and when you do, nothing will ever compare.And I realized Garrett was right about one thing: I had flipped. Completely.人性的美具有纷繁的多面性，无论是男女之爱还是亲人之情，所有的美都会令人向往和感动!</p>
      </div>

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/Flipped205
 - name: 邮箱
   icon: envelope-o
   href: /
 - name: 联系QQ
   icon: qq
   href: /
 - name: 微博
   icon: weibo
   href: /
 - name: QQ群
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 友链设置
links:
  - 个人博客: 


# 主题自定义个性化配置

## 网站宣传语
branding:

## 设置banner背景图片
banner:
    img: 

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 代码高亮配置
highlightTheme:

## ICON配置
fontAwesome: 

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: false
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="" target="_blank">Snippet</a>


## 主题评论

### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10

### 来必力
livere: 
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid: cyt8KmUC1
  conf: prod_855a68d3b3d91855360a6215672a505a

## 网站访问统计

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计
baidu_analytics: 

### 谷歌统计
google_analytics: 

### 腾讯分析
tencent_analytics: 

### 百度文章推送
baidu_push:

#网站主题配置
since: 2018
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
